# Tarefa 1-1: PyTorch 101

Antes de começar, coloque seu nome e RA no seguinte formato

: Nome SOBRENOME, #00000000   //   e.g.) Jurandy ALMEIDA, #12345678

**Sua Resposta:**   
Seu NOME, #XXXXXXXX

# Código de Configuração
Antes de começarmos, é precisamos executar algum código padrão para configurar nosso ambiente. Você precisará executar novamente este código de configuração sempre que iniciar o notebook.

Primeiro, execute esta célula para carregar a extensão [autoreload](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html?highlight=autoreload). Isso nos permite editar arquivos de origem `.py` e reimportá-los para o notebook para uma experiência de edição e depuração perfeita.

In [1]:
%load_ext autoreload
%autoreload 2

### Configuração do Google Colab
Em seguida, precisamos executar alguns comandos para configurar nosso ambiente no Google Colab. Se você estiver executando este notebook em uma máquina local, pode pular esta seção.

Execute a seguinte célula para montar seu Google Drive. Siga o link, entre na sua conta do Google (a mesma conta que você usou para armazenar este notebook!) E copie o código de autorização na caixa de texto que aparece abaixo.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Agora lembre-se do caminho em seu Google Drive onde você carregou este notebook, preencha-o abaixo. Se tudo estiver funcionando corretamente, a execução da célula a seguir deve imprimir os nomes dos arquivos da atribuição:

```
['a1_auxiliares.py', 'pytorch101.ipynb', 'pytorch101.py', 'rede_duas_camadas.ipynb', 'rede_duas_camadas.py', 'rnap']
```

In [ ]:
import os

# TODO: Preencha o caminho do Google Drive para onde você carregou a tarefa
# Exemplo: se você criar uma pasta 2020FA e colocar todos os arquivos na pasta A1, então '2020FA/A1'
# GOOGLE_DRIVE_PATH_AFTER_MYDRIVE = '2020FA/A1'
GOOGLE_DRIVE_PATH_AFTER_MYDRIVE = None 
GOOGLE_DRIVE_PATH = os.path.join('drive', 'My Drive', GOOGLE_DRIVE_PATH_AFTER_MYDRIVE)
print(os.listdir(GOOGLE_DRIVE_PATH))

Depois de montar com sucesso seu Google Drive e localizar o caminho para esta atribuição, execute a seguinte célula para permitir a importação dos arquivos `.py` desta atribuição. Se funcionar corretamente, deve imprimir a mensagem:

```
Olá do pytorch101.py!
```

bem como a última hora de edição do arquivo `pytorch101.py`.

In [ ]:
import sys
sys.path.append(GOOGLE_DRIVE_PATH)

import time, os
os.environ["TZ"] = "US/Eastern"
time.tzset()

from pytorch101 import ola
ola()

pytorch101_path = os.path.join(GOOGLE_DRIVE_PATH, 'pytorch101.py')
pytorch101_edit_time = time.ctime(os.path.getmtime(pytorch101_path))
print('pytorch101.py última edição em %s' % pytorch101_edit_time)

# Introdução

Python 3 e [PyTorch](https://pytorch.org/) serão usados ao longo do semestre, por isso é importante estar familiarizado com eles. Este material neste notebook foi extraido de http://cs231n.github.io/python-numpy-tutorial/ e https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb. Este material se concentra principalmente em PyTorch.

Este notebook irá guiá-lo por muitos dos recursos importantes do PyTorch que você precisará usar ao longo do semestre. Em algumas células e arquivos, você verá blocos de código semelhantes a este:

```python
##############################################################################
# TODO: Escreva a equação para uma linha
##############################################################################
pass
##############################################################################
#                             FIM DO SEU CÓDIGO                              #
##############################################################################
```

Você deve substituir a instrução `pass` por seu próprio código e deixar os blocos intactos, assim:

```python
##############################################################################
# TODO: Instruções sobre o que você precisa fazer
##############################################################################
y = m * x + b
##############################################################################
#                             FIM DO SEU CÓDIGO                              #
##############################################################################
```

Ao preencher o notebook, siga as seguintes regras:
- Não escreva ou modifique qualquer código fora dos blocos de código
- Não adicione ou exclua nenhuma célula do notebook. Você pode adicionar novas células para rascunhar sua resposta, mas excluí-las antes de enviar.
- Execute todas as células antes de enviar. Você só receberá nota pelo código que foi executado.

Este notebook contém muitas verificações de integridade para cada linha de código que você escreve. No entanto, **passar nessas verificações de integridade não significa que seu código está correto!** Durante a avaliação, podemos executar seu código em entradas adicionais e podemos olhar seu código para ter certeza de que você seguiu as diretrizes específicas para cada implementação. Você é encorajado a escrever casos de teste adicionais para as rotinas que você deve escrever, em vez de depender apenas das verificações de integridade do notebook.

# Python 3


Se você não está familiarizado com o Python 3, aqui estão algumas das mudanças mais comuns do Python 2 a serem observadas.

### Print é uma rotina

In [ ]:
print("Olá!")

Sem parênteses, a impressão não funcionará.

### Divisão de ponto flutuante por padrão

In [ ]:
5 / 2

Para fazer a divisão inteira, usamos duas barras invertidas:

In [ ]:
5 // 2

### Sem xrange

O xrange do Python 2 agora está mesclado com o "range" para Python 3 e não há xrange no Python 3. No Python 3, range(3) não cria uma lista de 3 elementos como faria no Python 2, apenas cria um iterador mais eficiente em termos de memória.

Consequentemente,

xrange em Python 3: não existe

range no Python 3: tem comportamento muito semelhante ao xrange do Python 2

In [ ]:
for i in range(3):
    print(i)

In [ ]:
range(3)

In [ ]:
# Se necessário, pode fazer o seguinte para obter 
# um comportamento semelhante ao range do Python 2:
print(list(range(3)))

# PyTorch

[PyTorch](https://pytorch.org/) é um arcabouço de aprendizado de máquina de código aberto. Basicamente, o PyTorch fornece alguns recursos principais:

- Um objeto **Tensor** multidimensional, semelhante a [numpy](https://numpy.org/), mas com aceleração de GPU.
- Um mecanismo de **autograd** otimizado para calcular automaticamente derivadas
- Uma API limpa e modular para desenvolver **modelos de aprendizado profundo**

Usaremos o PyTorch para todas as atribuições de programação ao longo do semestre. Este notebook se concentrará na **API Tensor**, já que é a parte principal do PyTorch que usaremos nas primeiras atribuições.

Você pode encontrar mais informações sobre o PyTorch seguindo um dos [tutoriais oficiais](https://pytorch.org/tutorials/) ou [lendo a documentação](https://pytorch.org/docs/stable/).

Para usar o PyTorch, primeiro precisamos importar o pacote `torch`.

Também verificamos a versão; as tarefas deste curso usarão o PyTorch versão 1.7.0, já que esta é a versão padrão do Google Colab.

In [ ]:
import torch
print(torch.__version__)

## Conceitos básicos sobre Tensor

### Criando e acessando tensores

Um **tensor** do `toch`  é um arranjo multidimensional de valores, todos do mesmo tipo, e é indexado por uma tupla de inteiros não negativos. O número de dimensões é o **posto** do tensor; o **shape** de um tensor é uma tupla de inteiros fornecendo o tamanho do arranjo ao longo de cada dimensão.

Podemos inicializar um tensor do `torch` a partir de listas aninhadas do Python. Podemos acessar ou modificar elementos de um tensor do PyTorch usando colchetes.

O acesso a um elemento de um tensor do PyTorch retorna um escalar do PyTorch; podemos converter isso para um escalar do Python usando o método `.item()`:

In [ ]:
# Cria um tensor de posto 1 a partir de uma lista do Python
a = torch.tensor([1, 2, 3])
print('Aqui está a:')
print(a)
print('type(a): ', type(a))
print('posto de a: ', a.dim())
print('a.shape: ', a.shape)

# Acessa os elementos usando colchetes
print()
print('a[0]: ', a[0])
print('type(a[0]): ', type(a[0]))
print('type(a[0].item()): ', type(a[0].item()))

# Altera os elementos usando colchetes
a[1] = 10
print()
print('a depois de alterado:')
print(a)

O exemplo acima mostra um tensor unidimensional; podemos da mesma forma criar tensores com duas ou mais dimensões:

In [ ]:
# Cria um tensor bidimensional
b = torch.tensor([[1, 2, 3], [4, 5, 5]])
print('Aqui está b:')
print(b)
print('posto de b:', b.dim())
print('b.shape: ', b.shape)

# Acessa elementos de um tensor multidimensional
print()
print('b[0, 1]:', b[0, 1])
print('b[1, 2]:', b[1, 2])

# Altera elementos de um tensor multidimensional
b[1, 1] = 100
print()
print('b depois de alterado:')
print(b)

Agora é a **sua vez**. No arquivo `pytorch101.py`, complete a implementação das rotinas `criar_tensor_de_exemplo`, `alterar_tensor` e `contar_elementos_do_tensor` para praticar a criação, alteração e entendimento sobre o shape dos tensores.

In [ ]:
from pytorch101 import criar_tensor_de_exemplo, alterar_tensor, contar_elementos_do_tensor

# Cria um tensor de exemplo
x = criar_tensor_de_exemplo()
print('Aqui está o tensor de exemplo:')
print(x)

# Altera o tensor pela modificação de alguns elementos
indices = [(0, 0), (1, 0), (1, 1)]
valores = [4, 5, 6]
alterar_tensor(x, indices, valores)
print('\nDepois de alterado:')
print(x)
print('\nO shape está correto: ', x.shape == (3, 2))
print('x[0, 0] está correto: ', x[0, 0].item() == 4)
print('x[1, 0] está correto: ', x[1, 0].item() == 5)
print('x[1, 1] está correto: ', x[1, 1].item() == 6)

# Verifica o número de elementos no tensor de exemplo
num = contar_elementos_do_tensor(x)
print('\nNúmero de elementos em x: ', num)
print('A contagem está correta: ', num == 6)

### Construtores de Tensor

PyTorch fornece muitos métodos convenientes para construir tensores; isso evita a necessidade de usar listas do Python. Por exemplo:

- [`torch.zeros`](https://pytorch.org/docs/1.1.0/torch.html#torch.zeros): Cria um tensor somente com zeros
- [`torch.ones`](https://pytorch.org/docs/1.1.0/torch.html#torch.ones): Cria um tensor somente com uns
- [`torch.rand`](https://pytorch.org/docs/1.1.0/torch.html#torch.rand): Cria um tensor com números aleatórios uniformes

Você pode encontrar uma lista completa de operações de criação de tensores [na documentação](https://pytorch.org/docs/stable/torch.html#creation-ops).

In [ ]:
# Cria um tensor somente com zeros
a = torch.zeros(2, 3)
print('tensor de zeros:')
print(a)

# Cria um tensor somente com uns
b = torch.ones(1, 2)
print('\ntensor de uns:')
print(b)

# Cria uma matriz identidade 3x3
c = torch.eye(3)
print('\nmatriz identidade:')
print(c)

# Tensor de valores aleatórios
d = torch.rand(4, 5)
print('\ntensor aleatório:')
print(d)

**Sua vez**: No arquivo `pytorch101.py`, complete a implementação de `criar_tensor_de_pi` para praticar o uso de um construtor de tensor.

Dica: [`torch.full`](https://pytorch.org/docs/stable/generated/torch.full.html#torch.full)

In [ ]:
from pytorch101 import criar_tensor_de_pi

x = criar_tensor_de_pi(4, 5)

print('x é um tensor:', torch.is_tensor(x))
print('x tem o shape correto: ', x.shape == (4, 5))
print('x está preenchido com pi: ', (x == 3.14).all().item() == 1)

### Tipos de dados

Nos exemplos acima, você deve ter notado que alguns de nossos tensores continham valores de ponto flutuante, enquanto outros continham valores inteiros.

PyTorch fornece um [grande conjunto de tipos de dados numéricos](https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype) que você pode usar para construir tensores. PyTorch tenta adivinhar um tipo de dados quando você cria um tensor; funções que constroem tensores normalmente têm um argumento `dtype` que você pode usar para especificar explicitamente um tipo de dados.

Cada tensor tem um atributo `dtype` que você pode usar para verificar seu tipo de dados:

In [ ]:
# Deixa o torch escolher o tipo de dados
x0 = torch.tensor([1, 2])   # Lista de inteiros
x1 = torch.tensor([1., 2.]) # Lista de reais
x2 = torch.tensor([1., 2])  # Lista mista
print('dtype quando torch escolhe por nós:')
print('Lista de inteiros:', x0.dtype)
print('Lista de reais:', x1.dtype)
print('Lista mista:', x2.dtype)

# Força um tipo de dados particular
y0 = torch.tensor([1, 2], dtype=torch.float32)  # 32-bit float
y1 = torch.tensor([1, 2], dtype=torch.int32)    # 32-bit (signed) integer
y2 = torch.tensor([1, 2], dtype=torch.int64)    # 64-bit (signed) integer
print('\ndtype quando nós forçamos um tipo de dados:')
print('32-bit float: ', y0.dtype)
print('32-bit integer: ', y1.dtype)
print('64-bit integer: ', y2.dtype)

# Outras opções de criação também usam um argumento dtype 
z0 = torch.ones(1, 2)  # Deixa o toch escolher por nós
z1 = torch.ones(1, 2, dtype=torch.int16) # 16-bit (signed) integer
z2 = torch.ones(1, 2, dtype=torch.uint8) # 8-bit (unsigned) integer
print('\ntorch.ones com diferentes dtypes')
print('dtype padrão:', z0.dtype)
print('16-bit integer:', z1.dtype)
print('8-bit unsigned integer:', z2.dtype)

Podemos **converter** um tensor para outro tipo de dados usando o método [`.to()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.to); também existem métodos de conveniência como [`.float()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.float) e [`.long()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.long) que convertem para tipos de dados específicos:

In [ ]:
x0 = torch.eye(3, dtype=torch.int64)
x1 = x0.float()  # Converte para 32-bit float
x2 = x0.double() # Converte para 64-bit float
x3 = x0.to(torch.float32) # Forma alteranativa de converter para 32-bit float
x4 = x0.to(torch.float64) # Forma alteranativa de converter para 64-bit float
print('x0:', x0.dtype)
print('x1:', x1.dtype)
print('x2:', x2.dtype)
print('x3:', x3.dtype)
print('x4:', x4.dtype)

PyTorch oferece várias maneiras de criar um tensor com o mesmo tipo de dados de outro tensor:

- PyTorch fornece construtores de tensores como [`torch.zeros_like()`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html#torch.zeros_like) que criam novos tensores com o mesmo shape e type de um determinado tensor
- Objetos de tensor têm métodos de instância, como [`.new_zeros()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.new_zeros) que criam tensores do mesmo tipo, mas possivelmente com formas diferentes
- O método de instância de tensor [`.to()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to) pode tomar um tensor como um argumento, caso em que ele converte para o tipo de dados do argumento.

In [ ]:
x0 = torch.eye(3, dtype=torch.float64)  # Shape (3, 3), dtype torch.float64
x1 = torch.zeros_like(x0)               # Shape (3, 3), dtype torch.float64
x2 = x0.new_zeros(4, 5)                 # Shape (4, 5), dtype torch.float64
x3 = torch.ones(6, 7).to(x0)            # Shape (6, 7), dtype torch.float64)
print('x0 shape é %r, dtype é %r' % (x0.shape, x0.dtype))
print('x1 shape é %r, dtype é %r' % (x1.shape, x1.dtype))
print('x2 shape é %r, dtype é %r' % (x2.shape, x2.dtype))
print('x3 shape é %r, dtype é %r' % (x3.shape, x3.dtype))

**Sua vez**: No arquivo `pytorch101.py`, implemente a rotina ` multiplos_de_dez` que deve criar e retornar um tensor de dtype `torch.float64` contendo todos os múltiplos de dez em um determinado intervalo.

Dica: [`torch.arange`](https://pytorch.org/docs/stable/generated/torch.arange.html#torch.arange)

In [ ]:
from pytorch101 import multiplos_de_dez

inicio = 5
fim = 25
x = multiplos_de_dez(inicio, fim)
print('O dtype está correto: ', x.dtype == torch.float64)
print('O shape está correto: ', x.shape == (2,))
print('Os valores estão corretos: ', x.tolist() == [10, 20])

# Se não houver múltiplos de dez no intervalo dado você deve retornar um tensor vazio
inicio = 5
fim = 7
x = multiplos_de_dez(inicio, fim)
print('\nO dtype está correto: ', x.dtype == torch.float64)
print('O shape está correto: ', x.shape == (0,))

Embora o PyTorch forneça um grande número de tipos de dados numéricos, os tipos de dados mais comumente usados são:

- `torch.float32`: Tipo de ponto flutuante padrão; usado para armazenar parâmetros aprendíveis, ativações de rede, etc. Quase toda a aritmética é feita usando este tipo.
- `torch.int64`: Normalmente usado para armazenar índices
- `torch.bool`: armazena valores booleanos: 0 é falso e 1 é verdadeiro
- `torch.float16`: Usado para aritmética de precisão mista, geralmente em GPUs NVIDIA com [núcleos tensores](https://www.nvidia.com/en-us/data-center/tensorcore/). Você não precisará se preocupar com este tipo de dados neste curso.

## Indexação de tensor

Já vimos como obter e definir elementos individuais de tensores PyTorch. O PyTorch também fornece muitas outras maneiras de indexar em tensores. Ficar confortável com essas diferentes opções torna mais fácil modificar diferentes partes de tensores com facilidade.

### Indexação de fatias

Semelhante a listas do Python e arranjos do numpy, os tensores do PyTorch podem ser **fatiados** usando a sintaxe `start:stop` ou `start:stop:step`. O índice `stop` é sempre não inclusivo: é o primeiro elemento a não ser incluído na fatia.

Os índices `start` e `stop` podem ser negativos, caso em que contam para trás a partir do final do tensor.

In [ ]:
a = torch.tensor([0, 11, 22, 33, 44, 55, 66])
print(0, a)        # (0) Tensor original
print(1, a[2:5])   # (1) Elementos entre os índices 2 e 5
print(2, a[2:])    # (2) Elementos após o índice 2
print(3, a[:5])    # (3) Elementos antes do índice 5
print(4, a[:])     # (4) Todos os elementos
print(5, a[1:5:2]) # (5) Cada segundo elemento entre os índices 1 e 5
print(6, a[:-1])   # (6) Todos exceto o último elemento
print(7, a[-4::2]) # (7) Cada segundo elemento, começando do quarto último

Para tensores multidimensionais, você pode fornecer uma fatia ou inteiro para cada dimensão do tensor a fim de extrair diferentes tipos de subtensores:

In [ ]:
# Cria o seguinte tensor de posto 2 com shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Tensor original:')
print(a)
print('shape: ', a.shape)

# Acessa a linha 1 e todas as colunas.
print('\nPrimeira linha:')
print(a[1, :])
print(a[1])  # Dá o mesmo resultado; podemos omitir para dimensões finais
print('shape: ', a[1].shape)

print('\nPrimeira coluna:')
print(a[:, 1])
print('shape: ', a[:, 1].shape)

# Acessa as duas primeiras linhas e as três últimas colunas
print('\nDuas primeiras linhas, duas últimas colunas:')
print(a[:2, -3:])
print('shape: ', a[:2, -3:].shape)

# Acessa cada segunda linha e colunas nos índices 1 e 2
print('\nEvery other row, middle columns:')
print(a[::2, 1:3])
print('shape: ', a[::2, 1:3].shape)

Existem duas maneiras comuns de acessar uma única linha ou coluna de um tensor: usar um inteiro reduzirá o posto para um e usar uma fatia de comprimento um manterá o mesmo posto. Observe que este é um comportamento diferente do MATLAB.

In [ ]:
# Cria o seguinte tensor de posto 2 com shape (3, 4)
a = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Tensor original')
print(a)

linha_r1 = a[1, :]    # View de posto 1 da segunda linha de a  
linha_r2 = a[1:2, :]  # View de posto 2 da segunda linha de a
print('\nDuas maneiras de acessar uma única linha:')
print(linha_r1, linha_r1.shape)
print(linha_r2, linha_r2.shape)

# Podemos fazer a mesma distinção ao acessar colunas:
coluna_r1 = a[:, 1]
coluna_r2 = a[:, 1:2]
print('\nDuas maneiras de acessar uma única coluna:')
print(coluna_r1, coluna_r1.shape)
print(coluna_r2, coluna_r2.shape)

O fatiamento de um tensor retorna uma **view** nos mesmos dados, portanto, modificá-lo também modificará o tensor original. Para evitar isso, você pode usar o método `clone()` para fazer uma cópia de um tensor.

In [ ]:
# Cria um tensor, uma fatia e uma cópia de uma fatia
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
b = a[0, 1:]
c = a[0, 1:].clone()
print('Antes de ser alterado:')
print(a)
print(b)
print(c)

a[0, 1] = 20  # a[0, 1] e b[0] apontam para o mesmo elemento
b[1] = 30     # b[1] e a[0, 2] apontam para o mesmo elemento
c[2] = 40     # c é uma cópia, logo tem seus próprios dados
print('\nDepois de ser alterado:')
print(a)
print(b)
print(c)

print(a.storage().data_ptr() == c.storage().data_ptr())

**Sua vez**: No arquivo `pytorch101.py`, implemente a rotina `pratica_de_indexacao_de_fatias` para praticar a indexação de tensores com diferentes tipos de fatias.

In [ ]:
# Usaremos esta rotina auxiliar para verificar seus resultados
def verifica(orig, atual, esperado):
    if not torch.is_tensor(atual):
        return False
    esperado = torch.tensor(esperado)
    mesmos_elementos = (atual == esperado).all().item()
    mesmos_dados = (orig.storage().data_ptr() == atual.storage().data_ptr())
    return mesmos_elementos and mesmos_dados

In [ ]:
from pytorch101 import pratica_de_indexacao_de_fatias

# Cria o seguinte tensor de posto 2 com shape (3, 5)
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]]
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
saida = pratica_de_indexacao_de_fatias(x)

ultima_linha = saida[0]
print('ultima_linha:')
print(ultima_linha)
correto = verifica(x, ultima_linha, [11, 12, 13, 14, 15])
print('Está correto: %r\n' % correto)

terceira_coluna = saida[1]
print('terceira_coluna:')
print(terceira_coluna)
correto = verifica(x, terceira_coluna, [[3], [8], [13]])
print('Está correto: %r\n' % correto)

primeiras_duas_linhas_tres_colunas = saida[2]
print('primeiras_duas_linhas_tres_colunas:')
print(primeiras_duas_linhas_tres_colunas)
correto = verifica(x, primeiras_duas_linhas_tres_colunas, [[1, 2, 3], [6, 7, 8]])
print('Está correto: %r\n' % correto)

linhas_pares_colunas_impares = saida[3]
print('linhas_pares_colunas_impares:')
print(linhas_pares_colunas_impares)
correto = verifica(x, linhas_pares_colunas_impares, [[2, 4], [12, 14]])
print('Está correcto: %r\n' % correto)

Até agora, usamos o fatiamento para **acessar** subtensores; também podemos usar o fatiamento para **modificar** subtensores escrevendo expressões de atribuição em que o lado esquerdo é uma expressão de fatia e o lado direito é uma constante ou um tensor de shape correto:

In [ ]:
a = torch.zeros(2, 4, dtype=torch.int64)
a[:, :2] = 1
a[:, 2:] = torch.tensor([[2, 3], [4, 5]])
print(a)

**Sua vez**: no arquivo `pytorch101.py`, implemente a rotina `pratica_atribuicao_de_fatias` para praticar a modificação de tensores com instruções de atribuição de fatias.

Esta rotina deve usar operações de atribuição de fatias para modificar as primeiras quatro linhas e as primeiras seis colunas do tensor de entrada para que sejam iguais a

$$
\begin{bmatrix}
0 & 1 & 2 & 2 & 2 & 2 \\
0 & 1 & 2 & 2 & 2 & 2 \\
3 & 4 & 3 & 4 & 5 & 5 \\
3 & 4 & 3 & 4 & 5 & 5 \\
\end{bmatrix}
$$

Sua implementação deve obedecer ao seguinte:
- Você deve alterar o próprio tensor x e retorná-lo
- Você só deve modificar as primeiras 4 linhas e as primeiras 6 colunas; todos os outros elementos devem permanecer inalterados
- Você só pode alterar o tensor usando operações de atribuição de fatia, onde você
atribui um número inteiro a uma fatia do tensor
- Você deve usar <= 6 operações de fatiamento para alcançar o resultado desejado

In [ ]:
from pytorch101 import pratica_atribuicao_de_fatias

x = torch.zeros(5, 7, dtype=torch.int64)
print('Aqui está x antes de chamar a rotina pratica_atribuicao_de_fatias:')
print(x)
pratica_atribuicao_de_fatias(x)
print('Aqui está x depois de chamar a rotina pratica_atribuicao_de_fatias:')
print(x)

esperado = [
    [0, 1, 2, 2, 2, 2, 0],
    [0, 1, 2, 2, 2, 2, 0],
    [3, 4, 3, 4, 5, 5, 0],
    [3, 4, 3, 4, 5, 5, 0],
    [0, 0, 0, 0, 0, 0, 0],
]
print('Está correto: ', x.tolist() == esperado)

### Indexação por tensor de inteiros

Quando você indexa no tensor do toch usando o fatiamento, a view com o tensor resultante sempre será um subtensor do tensor original. Isso é poderoso, mas pode ser restritivo.

Também podemos usar **arranjos de índices** para indexar tensores; isso nos permite construir novos tensores com muito mais flexibilidade do que usar fatias.

Como exemplo, podemos usar arranjo de índice para reordenar as linhas ou colunas de um tensor:

In [ ]:
# Cria o seguinte tensor de posto 2 com shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('Tensor original:')
print(a)

# Cria um novo tensor de shape (5, 4) pela reordenação das linhas de a:
# - As duas primeiras linhas são iguais à primeira linha de a
# - A terceira linha é igual a última linha de a
# - A quarta e quinta linhas são iguais à segunda linha de a
idx = [0, 0, 2, 1, 1]  # Arranjos de índices podem ser listas de inteiros do Python
print('\nLinhas reordenadas:')
print(a[idx])

# Cria um novo tensor de shape (3, 4) pela inversão das colunas de a
idx = torch.tensor([3, 2, 1, 0])  # Arranjos de índices podem ser tensores de int64 do toch
print('\nColunas reordenadas:')
print(a[:, idx])

De forma mais geral, dados arranjos de índices `idx0` e `idx1` com `N` elementos cada, `a[idx0, idx1]` é equivalente a:

```
torch.tensor([
  a[idx0[0], idx1[0]],
  a[idx0[1], idx1[1]],
  ...,
  a[idx0[N - 1], idx1[N - 1]]
])
```

(Um padrão semelhante se estende a tensores com mais de duas dimensões)

Podemos, por exemplo, usar isso para acessar ou alterar a diagonal de um tensor:

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Tensor original:')
print(a)

idx = [0, 1, 2]
print('\nAcessa a diagonal:')
print(a[idx, idx])

# Altera a diagonal
a[idx, idx] = torch.tensor([11, 22, 33])
print('\nDepois de alterar a diagonal:')
print(a)

Um truque útil com indexação por arranjos de inteiros é selecionar ou alterar um elemento de cada linha ou coluna de uma matriz:

In [ ]:
# Cria um novo tensor a partir do qual iremos selecionar elementos
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('Tensor original:')
print(a)

# Seleciona um elemento de cada linha de a:
# da linha 0, seleciona o elemento 1;
# da linha 1, seleciona o elemento 2;
# da linha 2, seleciona o elemento 1;
# da linha 3, seleciona o elemento 0
idx0 = torch.arange(a.shape[0])  # Maneira rápida de construir [0, 1, 2, 3]
idx1 = torch.tensor([1, 2, 1, 0])
print('\nSeleciona um elemento de cada linha:')
print(a[idx0, idx1])

# Agora altera cada um desses elementos para zero
a[idx0, idx1] = 0
print('\nDepois de modificar um elemento de cada linha:')
print(a)

**Sua vez**: no arquivo `pytorch101.py`, implemente as rotinas `embaralhar_colunas`, `inverter_linhas` e `pegar_um_elemento_por_coluna` para praticar o uso de indexação inteira para manipular tensores. Em cada uma dessas rotinas, sua implementação deve construir o tensor de saída **usando uma única operação de indexação na entrada**.

In [ ]:
from pytorch101 import embaralhar_colunas, inverter_linhas, pegar_um_elemento_por_coluna

# Cria um tensor de shape (4, 3):
# [[ 1,  2,  3],
#  [ 4,  5,  6],
#  [ 7,  8,  9],
#  [10, 11, 12]]
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('Aqui está x:')
print(x)

y1 = embaralhar_colunas(x)
print('\nAqui está embaralhar_colunas(x):')
print(y1)
esperado = [[1, 1, 3, 2], [4, 4, 6, 5], [7, 7, 9, 8], [10, 10, 12, 11]]
y1_correto = torch.is_tensor(y1) and y1.tolist() == esperado
print('Está correto: %r\n' % y1_correto)

y2 = inverter_linhas(x)
print('Aqui está inverter_linhas(x):')
print(y2)
esperado = [[10, 11, 12], [7, 8, 9], [4, 5, 6], [1, 2, 3]]
y2_correto = torch.is_tensor(y2) and y2.tolist() == esperado
print('Está correto: %r\n' % y2_correto)

y3 = pegar_um_elemento_por_coluna(x)
print('Aqui está pegar_um_elemento_por_coluna(x):')
print(y3)
esperado = [4, 2, 12]
y3_correto = torch.is_tensor(y3) and y3.tolist() == esperado
print('Está correto: %r' % y3_correto)

### Indexação por tensor de booleanos

A indexação por tensor de booleanos permite selecionar elementos arbitrários de um tensor de acordo com uma máscara booleana. Frequentemente, esse tipo de indexação é usada para selecionar ou modificar os elementos de um tensor que satisfazem alguma condição.

No PyTorch, usamos tensores de dtype `torch.bool` para manter máscaras booleanas.

(Antes da versão 1.2.0, não havia o tipo `torch.bool`, então, em vez disso, `torch.uint8` era geralmente usado para representar dados booleanos, com 0 indicando falso e 1 indicando verdadeiro. Cuidado com isso no código PyTorch mais antigo!)

In [ ]:
a = torch.tensor([[1,2], [3, 4], [5, 6]])
print('Tensor original:')
print(a)

# Encontra os elementos de a que são maiores que 3. A máscara tem 
# o mesmo shape que a, onde cada elemento da máscara diz se o elemento 
# correspondente de a é maior que três.
mask = (a > 3)
print('\nTensor de máscara:')
print(mask)

# Podemos usar a máscara para construir um tensor de posto 1 contendo 
# os elementos de a que são selecionados pela máscara
print('\nSelecionando elementos com a máscara:')
print(a[mask])

# Também podemos usar máscaras booleanas para modificar tensores; 
# por exemplo, isso altera todos os elementos <= 3 para zero:
a[a <= 3] = 0
print('\nDepois de modificar com uma máscara:')
print(a)

**Sua vez**: No arquivo `pytorch101.py`, implemente a rotina `contar_entradas_negativas` que conta o número de entradas negativas em um tensor do toch. Você pode fazer isso facilmente usando a indexação por tensor de booleanos. Sua implementação deve realizar apenas uma única operação de indexação no tensor de entrada.

In [ ]:
from pytorch101 import contar_entradas_negativas

# Cria alguns casos de teste
torch.manual_seed(598)
x0 = torch.tensor([[-1, -1, 0], [0, 1, 2], [3, 4, 5]])
x1 = torch.tensor([0, 1, 2, 3])
x2 = torch.randn(100, 100)
print('Está correto para x0: ', contar_entradas_negativas(x0) == 2)
print('Está correto para x1: ', contar_entradas_negativas(x1) == 0)
print('Está correto para x2: ', contar_entradas_negativas(x2) == 4984)

Agora implemente a rotina `cria_one_hot` que cria uma matriz de **vetores one-hot** a partir de uma lista de inteiros do Python.

Um vetor one-hot para um inteiro $n$ é um vetor que tem um na $n$-ésima entrada e zeros em todas as outras entradas. Vetores one-hot são comumente usados para representar variáveis categóricas em modelos de aprendizado de máquina.

Por exemplo, dada uma lista `[1, 4, 3, 2]` de inteiros, sua rotina deve produzir o tensor:

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```

Aqui, a primeira linha corresponde ao primeiro elemento da lista: ela tem um no índice 1 e zeros em todos os outros índices. A segunda linha corresponde ao segundo elemento da lista: tem um no índice 4 e zeros em todos os outros índices. As outras linhas seguem o mesmo padrão. A saída tem colunas suficientes para que nenhuma das linhas saia dos limites: o maior índice na entrada é 4, portanto, a matriz de saída tem 5 colunas.

In [ ]:
from pytorch101 import cria_one_hot

def verifica_one_hot(x, y):
    C = y.shape[1]
    for i, n in enumerate(x):
        if n >= C: return False
        for j in range(C):
            esperado = 1.0 if j == n else 0.0
            if y[i, j].item() != esperado: return False
        return True
      
x0 = [1, 4, 3, 2]
y0 = cria_one_hot(x0)
print('Aqui está y0:')
print(y0)
print('y0 está correto: ', verifica_one_hot(x0, y0))

x1 = [1, 3, 5, 7, 6, 2]
y1 = cria_one_hot(x1)
print('\nAqui está y1:')
print(y1)
print('y1 está correto: ', verifica_one_hot(x1, y1))

## Operações de remodelagem

### View

O PyTorch fornece muitas maneiras de manipular o shape dos tensores. O exemplo mais simples é [`.view()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.view): Isso retorna um novo tensor com o mesmo número de elementos que sua entrada, mas com um shape diferente.

Podemos usar `.view()` para achatar matrizes em vetores e para converter vetores de posto 1 em matrizes de linha ou coluna de posto 2:

In [ ]:
x0 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print('Tensor original:')
print(x0)
print('shape:', x0.shape)

# Achata x0 em um vetor de posto 1 de shape (8,)
x1 = x0.view(8)
print('\nTensor achatado:')
print(x1)
print('shape:', x1.shape)

# Converte x1 em um "vetor linha" de posto 2 de shape (1, 8)
x2 = x1.view(1, 8)
print('\nVetor linha:')
print(x2)
print('shape:', x2.shape)

# Converte x1 em um "vetor coluna" de posto 2 de shape (8, 1)
x3 = x1.view(8, 1)
print('\nVetor coluna:')
print(x3)
print('shape:', x3.shape)

# Converte x1 em um tensor de posto 3 de shape (2, 2, 2):
x4 = x1.view(2, 2, 2)
print('\nTensor de posto 3:')
print(x4)
print('shape:', x4.shape)

Por conveniência, chamadas para `.view()` podem incluir um único argumento -1; isso coloca elementos suficientes nessa dimensão para que a saída tenha o mesmo shape que a entrada. Isso torna mais fácil escrever algumas operações de remodelagem de uma forma que seja agnóstica ao shape do tensor:

In [ ]:
# Podemos reutilizar essas rotinas para tensores de diferentes formatos
def achata(x):
    return x.view(-1)

def cria_vetor_linha(x):
    return x.view(1, -1)

x0 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x0_achatado = achata(x0)
x0_linha = cria_vetor_linha(x0)
print('x0:')
print(x0)
print('x0_achatado:')
print(x0_achatado)
print('x0_row:')
print(x0_linha)

x1 = torch.tensor([[1, 2], [3, 4]])
x1_achatado = achata(x1)
x1_linha = cria_vetor_linha(x1)
print('\nx1:')
print(x1)
print('x1_achatado:')
print(x1_achatado)
print('x1_linha:')
print(x1_linha)

Como o próprio nome indica, um tensor retornado por `.view()` compartilha os mesmos dados da entrada, portanto, as alterações em um afetarão o outro e vice-versa:

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_achatado = x.view(-1)
print('x antes de modificar:')
print(x)
print('x_achatado antes de modificar:')
print(x_achatado)

x[0, 0] = 10   # x[0, 0] e x_achatado[0] apontam para os mesmos dados
x_achatado[1] = 20 # x_achatado[1] e x[0, 1] apontam para os mesmos dados

print('\nx após modificado:')
print(x)
print('x_achatado após modificado:')
print(x_achatado)

### Troca de eixos

Outra operação comum de remodelagem que você pode querer realizar é a transposição de uma matriz. Você pode se surpreender se tentar transpor uma matriz com `.view()`: A função `view()` pega os elementos em ordem de linha, então **você não pode transpor matrizes com `.view()`** .

Em geral, você só deve usar `.view()` para adicionar novas dimensões a um tensor, ou para concatenar dimensões adjacentes de um tensor.

Para outros tipos de operações de remodelagem, você geralmente precisa usar uma rotina que pode trocar os eixos de um tensor. A função mais simples é `.t()`, especificamente para transpor matrizes. Ela está disponível tanto como uma [função no módulo `torch`](https://pytorch.org/docs/stable/generated/torch.t.html#torch.t) e como um [método de instância de tensor]( https://pytorch.org/docs/stable/tensors.html#torch.Tensor.t):

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print('Matriz original:')
print(x)
print('\nTranspor com view NÃO FUNCIONA!')
print(x.view(3, 2))
print('\nMatriz transposta:')
print(torch.t(x))
print(x.t())

Para tensores com mais de duas dimensões, podemos usar a função [`torch.transpose`](https://pytorch.org/docs/stable/generated/torch.transpose.html#torch.transpose) para trocar dimensões arbitrárias, ou o método [`.permute`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.permute) para permutar dimensões arbitrariamente:

In [ ]:
# Cria um tensor de shape (2, 3, 4)
x0 = torch.tensor([
     [[1,  2,  3,  4],
      [5,  6,  7,  8],
      [9, 10, 11, 12]],
     [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]])
print('Tensor original:')
print(x0)
print('shape:', x0.shape)

# Troca eixos 1 e 2; shape é (2, 4, 3)
x1 = x0.transpose(1, 2)
print('\nTroca eixos 1 e 2:')
print(x1)
print(x1.shape)

# Permuta eixos; o argumento (1, 2, 0) significa:
# - Faça a dimensão antiga 1 aparecer na dimensão 0;
# - Faça a dimensão antiga 2 aparecer na dimensão 1;
# - Faça a dimensão antiga 0 aparecer na dimensão 2;
# Isso resulta em um tensor de shape (3, 4, 2)
x2 = x0.permute(1, 2, 0)
print('\nPermuta eixos')
print(x2)
print('shape:', x2.shape)

### Tensores contíguos

Algumas combinações de operações de remodelagem falharão com erros incompreensíveis. As razões exatas para isso têm a ver com a maneira como os tensores e view de tensores são implementados e estão além do escopo desta tarefa. No entanto, se você estiver curioso, [esta postagem no blog de Edward Yang](http://blog.ezyang.com/2019/05/pytorch-internals/) fornece uma explicação clara do problema.

O que você precisa saber é que normalmente pode superar esses tipos de erros chamando [`.contiguous()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.contiguous) antes de `.view()`, ou usando [`.reshape()`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) em vez de `.view( ) `.

In [ ]:
x0 = torch.randn(2, 3, 4)

try:
  # Esta sequência de operações de remodelagem irá falhar
  x1 = x0.transpose(1, 2).view(8, 3)
except RuntimeError as e:
  print(type(e), e)
  
# Podemos resolver o problema usando .contiguous() ou .reshape()
x1 = x0.transpose(1, 2).contiguous().view(8, 3)
x2 = x0.transpose(1, 2).reshape(8, 3)
print('x1 shape: ', x1.shape)
print('x2 shape: ', x2.shape)

### **Sua vez**

No arquivo `pytorch101.py`, implemente a rotina `pratica_remodelagem` para praticar o uso de operações de remodelagem em tensores. Dado o tensor de entrada unidimensional `x` contendo os números de 0 a 23 em ordem, ele deve ter o seguinte tensor de saída `y` de shape `(3, 8)` usando operações de remodelagem em x:


```
y = tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
            [ 4,  5,  6,  7, 16, 17, 18, 19],
            [ 8,  9, 10, 11, 20, 21, 22, 23]])
```

Dica: você precisará criar um tensor intermediário de posto 3

In [ ]:
from pytorch101 import pratica_remodelagem

x = torch.arange(24)
print('Aqui está x:')
print(x)
y = pratica_remodelagem(x)
print('Aqui está y:')
print(y)

esperado = [
    [0, 1,  2,  3, 12, 13, 14, 15],
    [4, 5,  6,  7, 16, 17, 18, 19],
    [8, 9, 10, 11, 20, 21, 22, 23]]
print('Está correto:', y.tolist() == esperado)

## Operações de tensor
Até agora, vimos como construir, acessar e remodelar tensores. Mas uma das razões mais importantes para usar tensores é para realizar cálculos! PyTorch fornece muitas operações diferentes para realizar cálculos em tensores.

### Operações por elemento

Funções matemáticas básicas operam elemento a elemento em tensores e estão disponíveis como sobrecargas de operador, como funções no módulo `torch` e como métodos de instância em objetos do torch; todos produzem os mesmos resultados:

In [ ]:
x = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6, 7, 8]], dtype=torch.float32)

# Soma elemento a elemento; todas dão o mesmo resultado
print('Soma elemento a elemento:')
print(x + y)
print(torch.add(x, y))
print(x.add(y))

# Subtração elemento a elemento
print('\nSubtração elemento a elemento:')
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

# Multiplicação elemento a elemento
print('\nMultiplicação elemento a elemento:')
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

# Divisão  elemento a elemento
print('\nDivisão  elemento a elemento')
print(x / y)
print(torch.div(x, y))
print(x.div(y))

# Potenciação elemento a elemento
print('\nPotenciação elemento a elemento')
print(x ** y)
print(torch.pow(x, y))
print(x.pow(y))

O Torch também fornece muitas funções matemáticas padrão; elas estão disponíveis como funções no módulo `torch` e como métodos de instância em tensores:

Você pode encontrar uma lista completa de todas as funções matemáticas disponíveis [na documentação](https://pytorch.org/docs/stable/torch.html#pointwise-ops); muitas funções no módulo `torch` têm métodos de instância correspondentes [em objetos tensor](https://pytorch.org/docs/stable/tensors.html).

In [ ]:
x = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)

print('Raiz quadrada:')
print(torch.sqrt(x))
print(x.sqrt())

print('\nFunções trigonométricas:')
print(torch.sin(x))
print(x.sin())
print(torch.cos(x))
print(x.cos())

### Operações de redução

Até agora, vimos operações aritméticas básicas em tensores que operam elemento a elemento. Às vezes, podemos desejar realizar operações que agregam parte ou a totalidade de um tensor, como uma soma; são chamadas de operações de **redução**.

Como as operações por elemento acima, a maioria das operações de redução estão disponíveis tanto como funções no módulo `torch` quanto como métodos de instância em objetos `tensor`.

A operação de redução mais simples é a soma. Podemos usar a função [`.sum()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.sum) (ou equivalentemente [`torch.sum`](https://pytorch.org/docs/stable/generated/torch.sum.html)\) para reduzir um tensor inteiro ou para reduzir ao longo de apenas uma dimensão do tensor usando o argumento `dim`:

In [ ]:
x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=torch.float32)
print('Tensor original:')
print(x)

print('\nSoma sobre tensor inteiro:')
print(torch.sum(x))
print(x.sum())

# Podemos somar cada linha:
print('\nSoma de cada linha:')
print(torch.sum(x, dim=0))
print(x.sum(dim=0))

# Podemos somar cada coluna:
print('\nSoma de cada coluna:')
print(torch.sum(x, dim=1))
print(x.sum(dim=1))

Outras operações de redução úteis incluem [`mean`](https://pytorch.org/docs/stable/torch.html#torch.mean), [`min`](https://pytorch.org/docs/stable/torch.html#torch.min), e [`max`](https://pytorch.org/docs/stable/torch.html#torch.max). Você pode encontrar uma lista completa de todas as operações de redução disponíveis [na documentação](https://pytorch.org/docs/stable/torch.html#reduction-ops).

Algumas operações de redução retornam mais de um valor; por exemplo, `min` retorna o valor mínimo sobre a dimensão especificada, bem como o índice onde o valor mínimo ocorre:

In [ ]:
x = torch.tensor([[2, 4, 3, 5], [3, 3, 5, 2]], dtype=torch.float32)
print('Tensor original:')
print(x, x.shape)

# Encontra o mínimo global e retorna apenas um único valor
print('\nMínimo global: ', x.min())

# Calcula o mínimo ao longo de cada coluna; obtemos o valor e a localização:
# O mínimo da primeira coluna é 2 e ele aparece no índice 0;
# o mínimo da segunda coluna é 3 e aparece no índice 1; etc
coluna_min_vals, coluna_min_idxs = x.min(dim=0)
print('\nMínimo ao longo de cada coluna:')
print('valores:', coluna_min_vals)
print('indices:', coluna_min_idxs)

# Calcula o mínimo ao longo de cada linha; obtemos o valor e o mínimo
linha_min_vals, linha_min_idxs = x.min(dim=1)
print('\nMínimo ao longo de cada linha:')
print('valores:', linha_min_vals)
print('indices:', linha_min_idxs)

As operações de redução *reduzem* o posto dos tensores: a dimensão sobre a qual você executa a redução será removida do shape da saída. Se você passar `keepdim = True` para uma operação de redução, a dimensão especificada não será removida; o tensor de saída terá, em vez disso, o shape de 1 nessa dimensão.

Quando você está trabalhando com tensores multidimensionais, pensar em linhas e colunas pode se tornar confuso; em vez disso, é mais útil pensar sobre o shape que resultará de cada operação. Por exemplo:

In [ ]:
# Cria um tensor de shape (128, 10, 3, 64, 64)
x = torch.randn(128, 10, 3, 64, 64)
print(x.shape)

# Calcula a média sobre a dimensão 1; shape agora é (128, 3, 64, 64)
x = x.mean(dim=1)
print(x.shape)

# Calcula a soma sobre a dimensão 2; shape agora é (128, 3, 64)
x = x.sum(dim=2)
print(x.shape)

# Calcula a média sobre a dimensão 1, mas evita que a dimensão seja eliminada 
# passando keepdim = True; shape agora é (128, 1, 64)
x = x.mean(dim=1, keepdim=True)
print(x.shape)

**Sua vez**: No arquivo `pytorch101.py`, implemente a rotina `zero_linha_min` que define o valor mínimo ao longo de cada linha de um tensor para zero. Você deve usar operações de redução e indexação e não deve usar nenhum loop explícito.

Dica: [`clone`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.clone), [`argmin`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.argmin)

In [ ]:
from pytorch101 import zero_linha_min

x0 = torch.tensor([[10, 20, 30], [2, 5, 1]])
print('Aqui está x0:')
print(x0)
y0 = zero_linha_min(x0)
print('Aqui está y0:')
print(y0)
esperado = [[0, 20, 30], [2, 5, 0]]
y0_correto = torch.is_tensor(y0) and y0.tolist() == esperado
print('y0 está correto: ', y0_correto)

x1 = torch.tensor([[2, 5, 10, -1], [1, 3, 2, 4], [5, 6, 2, 10]])
print('\nAqui está x1:')
print(x1)
y1 = zero_linha_min(x1)
print('Aqui está y1:')
print(y1)
esperado = [[2, 5, 10, 0], [0, 3, 2, 4], [5, 6, 0, 10]]
y1_correto = torch.is_tensor(y1) and y1.tolist() == esperado
print('y1 está correto: ', y1_correto)

### Operações matriciais

Observe que, ao contrário do MATLAB, * é uma multiplicação elemento a elemento, não uma multiplicação de matrizes. O PyTorch fornece várias funções de álgebra linear que calculam diferentes tipos de produtos de vetor e matriz. Os mais comumente usados ​​são:

- [`torch.dot`](https://pytorch.org/docs/stable/generated/torch.dot.html#torch.dot): Calcula o produto interno de vetores
- [`torch.mm`](https://pytorch.org/docs/stable/generated/torch.mm.html#torch.mm): Calcula produtos matriz-matriz
- [`torch.mv`](https://pytorch.org/docs/stable/generated/torch.mv.html#torch.mv): Calcula produtos vetoriais de matriz
- [`torch.addmm`](https://pytorch.org/docs/stable/generated/torch.addmm.html#torch.addmm) / [`torch.addmv`](https://pytorch.org/docs/stable/generated/torch.addmv.html#torch.addmv): Calcula multiplicações matriz-matriz e matriz-vetor mais um viés
- [`torch.bmm`](https://pytorch.org/docs/stable/generated/torch.bmm.html#torch.bmm) / [`torch.baddmm`](https://pytorch.org/docs/stable/generated/torch.baddbmm.html#torch.baddbmm): versões em lote de `torch.mm` e `torch.addmm`, respectivamente
- [`torch.matmul`](https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul): Produto de matriz arbitrária que executa operações diferentes dependendo do posto das entradas. Surpreendentemente, isso é semelhante a `np.dot` em numpy.

Você pode encontrar uma lista completa dos operadores de álgebra linear disponíveis [na documentação](https://pytorch.org/docs/stable/torch.html#blas-and-lapack-operations).

Aqui está um exemplo de uso de `torch.dot` para calcular produtos internos. Como os outros operadores matemáticos que vimos, a maioria dos operadores de álgebra linear estão disponíveis tanto como funções no módulo `torch` quanto como métodos de instância de tensores:

In [ ]:
v = torch.tensor([9,10], dtype=torch.float32)
w = torch.tensor([11, 12], dtype=torch.float32)

# Produto interno de vetores
print('Produto interno:')
print(torch.dot(v, w))
print(v.dot(w))

# dot funciona apenas para vetores -- ele dará um erro para tensores de posto > 1
x = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
y = torch.tensor([[5,6],[7,8]], dtype=torch.float32)
try:
  print(x.dot(y))
except RuntimeError as e:
  print(e)
  
# Em vez disso, usamos mm para produtos de matriz-matriz:
print('\nProduto de matriz-matriz:')
print(torch.mm(x, y))
print(x.mm(y))

Com todos os diferentes operadores de álgebra linear que o PyTorch oferece, geralmente há mais de uma maneira de computar algo. Por exemplo, para calcular produtos de matriz-vetor, podemos usar `torch.mv`; podemos remodelar o vetor para ter posto 2 e usar `torch.mm`; ou podemos usar `torch.matmul`. Todos fornecem os mesmos resultados, mas as saídas podem ter  diferentes postos:

In [ ]:
print('Aqui está x (posto 2):')
print(x)
print('\nAqui está v (posto 1):')
print(v)

# Produto de matriz-vetor com torch.mv produz uma saída de posto 1
print('\nProduto de matriz-vetor com torch.mv (saída de posto 1)')
print(torch.mv(x, v))
print(x.mv(v))

# Podemos remodelar o vetor para ter posto 2 e usar torch.mm para realizar 
# o produto de matriz-vetor, mas o resultado terá posto 2
print('\nProduto de matriz-vetor com torch.mm (saída de posto 2)')
print(torch.mm(x, v.view(2, 1)))
print(x.mm(v.view(2, 1)))

print('\nProduto de matriz-vetor com torch.matmul (saída de posto 1)')
print(torch.matmul(x, v))
print(x.matmul(v))

**Sua vez**: No arquivo `pytorch101.py`, implemente a função `multiplicacao_de_matriz_em_lote`. Você deve implementar dois caminhos dentro desta rotina: um que usa um loop explícito sobre a dimensão do lote e outro que executa a multiplicação da matriz em lote usando uma única operação do PyTorch e nenhum loop explícito.

Dica: [`torch.stack`](https://pytorch.org/docs/master/generated/torch.stack.html), [`bmm`](https://pytorch.org/docs/stable/generated/torch.bmm.html#torch.bmm)

In [ ]:
from pytorch101 import multiplicacao_de_matriz_em_lote

B, N, M, P = 2, 3, 5, 4
x = torch.randn(B, N, M)
y = torch.randn(B, M, P)
z_esperado = torch.stack([x[0] @ y[0], x[1] @ y[1]])

# Os dois podem não retornar exatamente o mesmo resultado; diferentes rotinas de 
# álgebra linear frequentemente retornam resultados ligeiramente diferentes devido 
# ao fato de que a matemática de ponto flutuante é não exata e não associativa.
z1 = multiplicacao_de_matriz_em_lote(x, y, usa_loop=True)
z1_dif = (z1 - z_esperado).abs().max().item()
print('z1 diferença: ', z1_dif)
print('z1 diferença dentro da tolerância: ', z1_dif < 1e-6)

z2 = multiplicacao_de_matriz_em_lote(x, y, usa_loop=False)
z2_dif = (z2 - z_esperado).abs().max().item()
print('\nz2 diferença: ', z2_dif)
print('z2 diferença dentro da tolerância: ', z2_dif < 1e-6)

### Vetorização

Em muitos casos, evitar loops explícitos do Python em seu código e, em vez disso, usar os operadores do PyTorch para lidar com o loop interno fará com que seu código seja executado muito mais rápido. Este estilo de escrever código, denominado **vetorização**, evita a sobrecarga do interpretador Python e também pode paralelizar melhor a computação (por exemplo, entre núcleos de CPU, em GPUs). Sempre que possível, você deve se esforçar para escrever código vetorizado.

Execute o seguinte para comparar a velocidade de `multiplicacao_de_matriz_em_lote` com` usa_loop = True` e com `usa_loop = False`.

In [ ]:
import time
import matplotlib.pyplot as plt
from pytorch101 import multiplicacao_de_matriz_em_lote

N, M, P = 100, 100, 100
tempos_com_loop = []
tempos_sem_loop = []
Bs = list(range(5, 100, 5))
num_repeticoes = 20
for B in Bs:
    repeticoes_com_loop = []
    repeticoes_sem_loop = []
    for rep in range(num_repeticoes):
        x = torch.randn(B, N, M)
        y = torch.randn(B, M, P)
        t0 = time.time()
        z1 = multiplicacao_de_matriz_em_lote(x, y, usa_loop=True)
        t1 = time.time()
        z2 = multiplicacao_de_matriz_em_lote(x, y, usa_loop=False)
        t2 = time.time()
        repeticoes_com_loop.append(t1 - t0)
        repeticoes_sem_loop.append(t2 - t1)
    media_com_loop = torch.tensor(repeticoes_com_loop).mean().item()
    media_sem_loop = torch.tensor(repeticoes_sem_loop).mean().item()
    tempos_com_loop.append(media_com_loop)
    tempos_sem_loop.append(media_sem_loop)
    
plt.plot(Bs, tempos_com_loop, 'o-', label='usa_loop=True')
plt.plot(Bs, tempos_sem_loop, 'o-', label='usa_loop=False')
plt.xlabel('Tamanho do lote B')
plt.ylabel('Tempo de execução (s)')
plt.legend()
plt.show()

## Transmissão

A transmissão é um mecanismo poderoso que permite ao PyTorch trabalhar com matrizes de diferentes formatos ao realizar operações aritméticas. Frequentemente, temos um tensor menor e um tensor maior, e queremos usar o tensor menor várias vezes para realizar alguma operação no tensor maior.

Por exemplo, suponha que desejamos adicionar um vetor constante a cada linha de um tensor. Podemos fazer assim:

In [ ]:
# Vamos adicionar o vetor v a cada linha da matriz x, 
# armazenando o resultado na matriz y
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
y = torch.zeros_like(x)   # Cria uma matriz vazia com o mesmo shape de x

# Adiciona o vetor v a cada linha da matriz x com um loop explícito
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

Isso funciona; entretanto, quando o tensor x é muito grande, computar um loop explícito em Python pode ser lento. Observe que adicionar o vetor v a cada linha do tensor x é equivalente a formar um tensor vv ao empilhar várias cópias de v verticalmente e, em seguida, realizar a soma de elemento a elemento de x e vv. Poderíamos implementar essa abordagem assim:

In [ ]:
vv = v.repeat((4, 1))  # Empilha 4 cópias de v uma em cima do outra
print(vv)              # Imprime "[[1 0 1]
                       #           [1 0 1]
                       #           [1 0 1]
                       #           [1 0 1]]"

In [ ]:
y = x + vv  # Adiciona x e vv elemento a elemento
print(y)

A transmissão do PyTorch nos permite realizar esse cálculo sem realmente criar várias cópias de v. Considere esta versão, usando a transmissão:

In [ ]:
# Vamos adicionar o vetor v a cada linha da matriz x, 
# armazenando o resultado na matriz y
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
y = x + v  # Adiciona v a cada linha de x usando a transmissão
print(y)

A linha y = x + v funciona mesmo que x tenha o shape (4, 3) e v tenha o shape (3,) devido à transmissão; esta linha funciona como se v realmente tivesse shape (4, 3), onde cada linha era uma cópia de v, e a soma era executada elemento a elemento.

A transmissão de dois tensores juntos segue estas regras:

1. Se os tensores não tiverem o mesmo posto, prefixe o shape da matriz de posto inferior com 1s até que ambas os formatos tenham o mesmo comprimento.
2. Os dois tensores são considerados *compatíveis* em uma dimensão se eles tiverem o mesmo tamanho na dimensão, ou se um dos tensores tiver tamanho 1 nessa dimensão.
3. Os tensores podem ser transmitidos juntos se forem compatíveis em todas as dimensões.
4. Após a transmissão, cada tensor se comporta como se tivesse shape igual ao máximo elemento a elemento dos formatos dos dois tensores de entrada.
5. Em qualquer dimensão onde um tensor tinha tamanho 1 e o outro tensor tinha tamanho maior que 1, o primeiro tensor se comporta como se tivesse sido copiado ao longo dessa dimensão

Se esta explicação não fizer sentido, tente ler a explicação da [documentação](https://pytorch.org/docs/stable/notes/broadcasting.html).

A transmissão geralmente acontece implicitamente dentro de muitos operadores do PyTorch. No entanto, também podemos transmitir explicitamente usando a função [`torch.broadcast_tensors`](https://pytorch.org/docs/stable/generated/torch.broadcast_tensors.html#torch.broadcast_tensors):

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
print('Aqui está x (antes da transmissão):')
print(x)
print('x.shape: ', x.shape)
print('\nAqui está v (antes da transmissão):')
print(v)
print('v.shape: ', v.shape)

xx, vv = torch.broadcast_tensors(x, v)
print('Aqui está xx (depois da transmissão):')
print(xx)
print('xx.shape: ', x.shape)
print('\nAqui está vv (depois da transmissão):')
print(vv)
print('vv.shape: ', vv.shape)

Observe que após a transmissão, `x` permanece o mesmo, mas `v` tem uma dimensão extra anexada ao seu shape e é duplicado para ter o mesmo shape que `x`; como eles têm o mesmo shape após a transmissão, eles podem ser adicionados aos poucos.

Nem todas as funções suportam transmissão. Você pode encontrar funções que não oferecem suporte à transmissão dos documentos oficiais. (por exemplo, [`torch.mm`](https://pytorch.org/docs/stable/torch.html#torch.mm) não oferece suporte a transmissão, mas [`torch.matmul`](https://pytorch.org/docs/1.1.0/torch.html#torch.matmul) faz)

A transmissão pode nos permitir implementar facilmente muitas operações diferentes. Por exemplo, podemos calcular um produto externo de vetores:

In [ ]:
# Calcula o produto externo de vetores
v = torch.tensor([1, 2, 3])  # v tem shape (3,)
w = torch.tensor([4, 5])     # w tem shape (2,)
# Para calcular um produto externo, primeiro remodelamos v para ser um 
# vetor coluna de shape (3, 1); podemos então transmiti-lo contra w para 
# produzir uma saída de shape (3, 2), que é o produto externo de v e w:
print(v.view(3, 1) * w)

Podemos adicionar um vetor a cada linha de uma matriz:




In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # x tem shape (2, 3)
v = torch.tensor([1, 2, 3])               # v tem shape (3,)
print('Aqui está a matriz:')
print(x)
print('\nAqui está o vetor:')
print(v)

# x tem shape (2, 3) e v tem shape (3,) logo eles transmitem para (2, 3),
# resultando na seguinte matriz:
print('\nAdiciona o vetor a cada linha da matriz:')
print(x + v)

Podemos adicionar um vetor a cada linha de uma matriz:

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # x tem shape (2, 3)
w = torch.tensor([4, 5])                  # w tem shape (2,)
print('Aqui está a matriz:')
print(x)
print('\nAqui está o vetor:')
print(w)

# x tem shape (2, 3) e w tem shape (2,). Remodelamos w para (2, 1);
# então, quando adicionamos os dois, o resultado transmite para (2, 3):
print('\nAdiciona o vetor a cada linha da matriz:')
print(x + w.view(-1, 1))

# Outra solução é a seguinte:
# 1. Transponha x para que tenha shape (3, 2)
# 2. Como w tem shape (2,), adicionar irá transmitir para (3, 2)
# 3. Transponha o resultado, resultando em um shape (2, 3)
print((x.t() + w).t())

Multiplique um tensor por um conjunto de constantes:

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # x tem shape (2, 3)
c = torch.tensor([1, 10, 11, 100])        # c tem shape (4)
print('Aqui está a matriz:')
print(x)
print('\nAqui está o vetor:')
print(c)

# Fazemos o seguinte:
# 1. Remodele c de (4,) para (4, 1, 1)
# 2. x tem shape (2, 3). Como eles têm postos diferentes, quando multiplicamos 
#    os dois, x se comporta como se seu shape fosse (1, 2, 3)
# 3. O resultado da multiplicação transmitida entre tensores de shape
#    (4, 1, 1) e (1, 2, 3) tem shape (4, 2, 3)
# 4. O resultado  y tem shape (4, 2, 3), e y[i] (shape (2, 3)) é igual a
#    c[i] * x
y = c.view(-1, 1, 1) * x
print('\nMultiplica x por um conjunto de constantes:')
print(y)

**Sua vez**: No arquivo `pytorch101.py`, implemente a rotina `normaliza_colunas` que normaliza as colunas de uma matriz. Ele deve calcular a média e o desvio padrão de cada coluna, depois subtrair a média e dividir pelo desvio padrão de cada elemento da coluna.

Exemplo:
```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
- A primeira coluna tem média 0 e desvio padrão 1
- A segunda coluna tem média 20 e desvio padrão 10
- A terceira coluna tem média 400 e desvio padrão 200

Após normalizar as colunas, o resultado deve ser:
```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

Lembre-se de que dados escalares $x_1,\ldots,x_M$ a média $\mu$ e o desvio padrão $\sigma$ são dados por

$$\mu=\frac{1}{M}\sum_{i=1}^M x_i \hspace{4pc} \sigma = \sqrt{\frac{1}{M-1}\sum_{i=1}^M(x_i-\mu)^2}$$

In [ ]:
from pytorch101 import normaliza_colunas

x = torch.tensor([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y = normaliza_colunas(x)
print('Aqui está x:')
print(x)
print('Aqui está y:')
print(y)

x_esperado = [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]
y_esperado = [[0., 1., 1.], [1., -1., -1.], [-1., 0., 0.]]
y_correto = y.tolist() == y_esperado
x_correto = x.tolist() == x_esperado
print('y está correto: ', y_correto)
print('x está inalterado: ', x_correto)

### Operadores out-of-place vs in-place

A maioria dos operadores do PyTorch são classificados em uma de duas categorias:
- **Operadores out-of-place:** retornam um novo tensor. A maioria dos operadores do PyTorch se comporta dessa maneira.
- **Operadores in-place:** modifica e retorna o tensor de entrada. Métodos de instância que terminam com um sublinhado (como `add_()`) são in-place. Os operadores no namespace `torch` podem ser executados in-place usando o argumento de palavra-chave `out = `.

Por exemplo:

In [ ]:
# A adição out-of-place cria e retorna um novo tensor sem modificar as entradas:
x = torch.tensor([1, 2, 3])
y = torch.tensor([3, 4, 5])
print('Adição out-of-place:')
print('Antes da adição:')
print('x: ', x)
print('y: ', y)
z = x.add(y)  # Igual a z = x + y ou z = torch.add(x, y)
print('\nApós a adição (x e y inalterados):')
print('x: ', x)
print('y: ', y)
print('z: ', z)
print('z é x: ', z is x)
print('z é y: ', z is y)

# A adição in-place modifica o tensor de entrada:
print('\n\nAdição in-place:')
print('Antes da adição:')
print('x: ', x)
print('y: ', y)
x.add_(y)  # Igual a x += y ou torch.add(x, y, out=x)
print('\nApós a adição (x é modificado):')
print('x: ', x)
print('y: ', y)
print('z: ', z)
print('z é x: ', z is x)
print('z é y: ', z is y)

Em geral, **você deve evitar operações in-place**, pois elas podem causar problemas ao calcular gradientes usando o autograd (que abordaremos em uma tarefa futura).

## Executando em GPU

Um dos recursos mais importantes do PyTorch é que ele pode usar unidades de processamento gráfico (GPUs) para acelerar suas operações de tensor.

Podemos verificar facilmente se o PyTorch está configurado para usar GPUs:

Os tensores podem ser movidos para qualquer dispositivo usando o método `.to`.

In [ ]:
import torch

if torch.cuda.is_available:
  print('PyTorch pode usar GPUs!')
else:
  print('PyTorch não pode usar GPUs.')

Você pode habilitar GPUs no Colab via Runtime -> Change Runtime Type -> Hardware Accelerator -> GPU.

Isso pode fazer com que o tempo de execução do Colab seja reiniciado, então vamos reimportar o torch na próxima célula.

Já vimos que os tensores do PyTorch têm um atributo `dtype` especificando seu tipo de dados. Todos os tensores do PyTorch também têm um atributo `device` que especifica o dispositivo onde o tensor está armazenado - CPU ou CUDA (para GPUs NVIDA). Um tensor em um dispositivo CUDA usará automaticamente esse dispositivo para acelerar todas as suas operações.

Assim como com tipos de dados, podemos usar o método [`.to()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.to) para alterar o dispositivo de um tensor. Também podemos usar os métodos de conveniência `.cuda()` e `.cpu()` para mover tensores entre CPU e GPU.

In [ ]:
# Constrói um tensor na CPU
x0 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print('x0 device:', x0.device)

# Move ele para a GPU usando .to()
x1 = x0.to('cuda')
print('x1 device:', x1.device)

# Move ele para a GPU usando .cuda()
x2 = x0.cuda()
print('x2 device:', x2.device)

# Move ele de volta para a CPU usando .to()
x3 = x1.to('cpu')
print('x3 device:', x3.device)

# Move ele de volta para a CPU usando .cpu()
x4 = x2.cpu()
print('x4 device:', x4.device)

# Podemos construir tensores diretamente na GPU também
y = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64, device='cuda')
print('y device / dtype:', y.device, y.dtype)

# Chamar x.to(y) onde y é um tensor retornará uma cópia de x com o mesmo 
# device e dtype de y
x5 = x0.to(y)
print('x5 device / dtype:', x5.device, x5.dtype)

Executar grandes operações de tensor em uma GPU pode ser **muito mais rápido** do que executar a operação equivalente na CPU.

Aqui, comparamos a velocidade de adição de dois tensores de shape (10000, 10000) na CPU e GPU:

(Observe que o código da GPU pode ser executado de forma assíncrona com o código da CPU, portanto, ao cronometrar a velocidade das operações na GPU, é importante usar `torch.cuda.synchronize` para sincronizar a CPU e a GPU.)

In [ ]:
import time

a_cpu = torch.randn(10000, 10000, dtype=torch.float32)
b_cpu = torch.randn(10000, 10000, dtype=torch.float32)

a_gpu = a_cpu.cuda()
b_gpu = b_cpu.cuda()
torch.cuda.synchronize()

t0 = time.time()
c_cpu = a_cpu + b_cpu
t1 = time.time()
c_gpu = a_gpu + b_gpu
torch.cuda.synchronize()
t2 = time.time()

# Verifica se eles calcularam a mesma coisa
dif = (c_gpu.cpu() - c_cpu).abs().max().item()
print('Diferença máxima entre c_gpu e c_cpu:', dif)

tempo_cpu = 1000.0 * (t1 - t0)
tempo_gpu = 1000.0 * (t2 - t1)
print('Tempo CPU: %.2f ms' % tempo_cpu)
print('Tempo GPU: %.2f ms' % tempo_gpu)
print('Ganho GPU: %.2f x' % (tempo_cpu / tempo_gpu))

Você deve ver que executar o mesmo cálculo na GPU foi mais de 10~30 vezes mais rápido do que na CPU! Devido às grandes acelerações que as GPUs oferecem, usaremos as GPUs para acelerar muito do nosso código de aprendizado de máquina a partir da próxima tarefa.

**Sua vez**: Use a GPU para acelerar a seguinte operação de multiplicação de matrizes. Você deve ver um ganho de 5~10x usando a GPU.

In [ ]:
import time
from pytorch101 import mm_na_cpu, mm_na_gpu

x = torch.rand(512, 4096)
w = torch.rand(4096, 4096)

t0 = time.time()
y0 = mm_na_cpu(x, w)
t1 = time.time()

y1 = mm_na_gpu(x, w)
torch.cuda.synchronize()
t2 = time.time()

print('y1 na CPU:', y1.device == torch.device('cpu'))
dif = (y0 - y1).abs().max().item()
print('Diferença máxima entre y0 e y1:', dif)
print('Diferença dentro da tolerância:', dif < 5e-2)

tempo_cpu = 1000.0 * (t1 - t0)
tempo_gpu = 1000.0 * (t2 - t1)
print('Tempo CPU: %.2f ms' % tempo_cpu)
print('Tempo GPU: %.2f ms' % tempo_gpu)
print('Ganho GPU: %.2f x' % (tempo_cpu / tempo_gpu))

Feito! Agora você pode ir para rede_duas_camadas.ipynb. Antes de ir, verifique se você gerou alguma célula adicional em cada arquivo ipynb (por exemplo, célula vazia após a última célula de código).